### ISSUE TITLE
protolint.yaml: File paths are not uniformly handled in UNIX and Windows

### ISSUE THREAD

**Issue by danvd** [yoheimuta/protolint#143]
When linting proto files in other than root folder, overrides to separate file paths must be written 2 times to ensure proper handling in both OS versions.

This variant is properly handled in UNIX only:
```
# Lint directives.
lint:
  # Linter files to ignore.
  ignores:
    - id: MESSAGE_NAMES_UPPER_CAMEL_CASE
      files:
        - ../proto/simple.proto
```
This variant is properly handled in Windows only:
```
# Lint directives.
lint:
  # Linter files to ignore.
  ignores:
    - id: MESSAGE_NAMES_UPPER_CAMEL_CASE
      files:
        - ..\proto\simple.proto
```

So to make it uniform one have to duplicate each path entry like this:
```
# Lint directives.
lint:
  # Linter files to ignore.
  ignores:
    - id: MESSAGE_NAMES_UPPER_CAMEL_CASE
      files:
        - ../proto/simple.proto
        - ..\proto\simple.proto
```

It would be great if UNIX paths will be properly accepted by Windows version of protolint.
