### ISSUE TITLE
Problems Running in CI / Docker for Latest?

### ISSUE THREAD

**Issue by steve-gray** [yoheimuta/protolint#174]
Am using Drone CI, and I'm finding that as of the last few days the protolint stage in our repos is failing. No error message, the pod just suddenly terminates. Its as if the entry/command isn't running for the container.....

![image](https://user-images.githubusercontent.com/14563775/133854818-e8bb6e3f-4167-41b1-b831-26a372df7813.png)

The issue seems to be as of v0.33.0 onward. Reverting to 0.32.0 is fine. The CI block being used in drone is fairly straightforward. The below works for 0.32, but not 0.33 onward:

```
- name: proto_lint
  image: yoheimuta/protolint:v0.32.0
  commands:
    - protolint ./proto/*.proto
  depends_on: []
```

Has the way the command needs to be invoked changed or something else about the container entry point changed?
