### ISSUE TITLE
pre-commit issues a warning

### ISSUE THREAD

**Issue by dnwillia-work** [yoheimuta/protolint#334]
Running it locally with the configuration from your readme issues the following warning:

[WARNING] The 'rev' field of repo 'https://github.com/yoheimuta/protolint' appears to be a mutable reference (moving tag / branch).  Mutable references are never updated after first install and are not supported.  See https://pre-commit.com/#using-the-latest-version-for-a-repository for more details.  Hint: `pre-commit autoupdate` often fixes this.

Maybe just update the README to say:
```
- repo: https://github.com/yoheimuta/protolint
  rev: <version> # Select a release here
  hooks:
  - id: protolint
```
