### ISSUE TITLE
Exclude directories via pattern

### ISSUE THREAD

**Issue by Kresshy** [yoheimuta/protolint#348]
Is it possible to exclude directories from the linter via a pattern? Something like a glob: `**/build` which would match every build directory from the root to other sub directories.

```yaml
lint:
  rules:
    all_default: true

  directories:
    exclude:
      - **/build
```
