### ISSUE TITLE
Configure rule severity via protolint config

### ISSUE THREAD

**Issue by profhenry** [yoheimuta/protolint#416]
https://github.com/yoheimuta/protolint/pull/335 introduced the severity feature. By default all rules have the ERROR severity. It seems that it was intended to configure the severity for a rule via the protolint config file. Unfortunately this does not work :-/.

For example when adding
```yaml
rules_option:
    max_line_length:
      severity: warning
```
to the protolint config you get the following error

```
yaml: unmarshal errors:
  line 26: field severity not found in type config.MaxLineLengthOption
```
